defmodule HelloPhoenix.Repo.Migrations.Stats2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      # remove :post_stats_id

      add :post_stats_id2, :uuid
    end
  end

  def down do
    alter table(:posts) do
      remove :post_stats_id2
      # This is the `down` migration of the statement:
      #
      #     remove :post_stats_id
      #

      # add :post_stats_id, :uuid
    end
  end
end