defmodule HelloPhoenix.Repo.Migrations.AdaddPostStatsId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add :post_stats_id, :uuid
    end
  end

  def down do
    alter table(:posts) do
      remove :post_stats_id
    end
  end
end